// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.App_context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDpcontex))]
    [Migration("20260918143258_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Adel @gmail.com",
                            FullName = "Alice Johnson",
                            Phone = "01012345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Ali @gmail.com",
                            FullName = "Bob Smith",
                            Phone = "01098765432"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Ahmed @gmail.com",
                            FullName = "Charlie Brown",
                            Phone = "01056789012"
                        },
                        new
                        {
                            Id = 4,
                            Email = "David @gmail.com",
                            FullName = "David Lee",
                            Phone = "01034567890"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Eva @gmail.com",
                            FullName = "Eva Green",
                            Phone = "01067890123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Frank @gmail.com",
                            FullName = "Frank White",
                            Phone = "01023456789"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 300,
                            Category = "Technology",
                            Description = "A conference on the latest trends in technology",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "Tech Conference 2024",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 200,
                            Category = "Music",
                            Description = "A festival featuring performances by renowned musicians",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            EventDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Title = "Music Festival",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 150,
                            Category = "Art",
                            Description = "A exhibition showcasing contemporary art",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            EventDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Art Exhibition",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 250,
                            Category = "Business",
                            Description = "A summit for business leaders and entrepreneurs",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "Business Summit",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 400,
                            Category = "Food",
                            Description = "A festival celebrating culinary delights from around the world",
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            EventDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            Title = "Food Festival",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 100,
                            Category = "Film",
                            Description = "A screening of an award-winning film followed by a Q&A session with the director",
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            EventDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            Title = "Film Screening",
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Adel@gmail.com",
                            FullName = "John Doe",
                            Phone = "010234567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Ali @gmail.com",
                            FullName = "Jane Smith",
                            Phone = "010987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Ahmed@gmail.com",
                            FullName = "Ahmed Hassan",
                            Phone = "010123456789"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("EventId", "AttendeeId")
                        .IsUnique();

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            AttendeeId = 1,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2535),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 2,
                            AttendeeId = 2,
                            EventId = 2,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2590),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 3,
                            AttendeeId = 3,
                            EventId = 3,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2593),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 4,
                            AttendeeId = 4,
                            EventId = 4,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2595),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 5,
                            AttendeeId = 5,
                            EventId = 5,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2597),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 6,
                            AttendeeId = 6,
                            EventId = 6,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2600),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 7,
                            AttendeeId = 2,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2602),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 8,
                            AttendeeId = 3,
                            EventId = 2,
                            RegistrationDate = new DateTime(2026, 9, 18, 17, 32, 57, 767, DateTimeKind.Local).AddTicks(2604),
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            Location = "123 Main St, Cityville",
                            Name = "Grand Hall"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 200,
                            Location = "456 Elm St, Townsville",
                            Name = "Conference Center"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1000,
                            Location = "789 Oak St, Villagetown",
                            Name = "Outdoor Arena"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Event", b =>
                {
                    b.HasOne("WebApplication1.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WebApplication1.Models.Registration", b =>
                {
                    b.HasOne("WebApplication1.Models.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebApplication1.Models.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("WebApplication1.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("WebApplication1.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("WebApplication1.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
